### PR TITLE
Update client versions

### PR DESCRIPTION
**Pull request by sorshion**
Fix; Precondition check failed

### CODE REVIEW

**Comment by sorshion** [comment]
#186

**Comment by sorshion** [comment]
[other project](https://github.com/yt-dlp/yt-dlp/issues/9316)

**Comment by kolipavan011** [comment]
> #186

Thank you sir, Problem is solved

**Comment by modemmike** [comment]
so we just need to use "athlon1600/youtube-downloader": "dev-master#047bb555cbef6fb18862ca377e1ba9bab9610196" for now until this has been merged?

**Comment by sorshion** [comment]
don't sync

**Pull request closed without merging**
