### PR TITLE
Youtube Sep18 Sig changes

### PR DESCRIPTION
**Pull request by arjunae**
.... Forked the same repo a while ago and implemented the Signature change needed for  youtubes sep18 base.js updates. 
Feel free to use them too.

### CODE REVIEW

**Comment by FaArIsH** [comment]
720p links are not getting or downloading only 360p and lower working

**Comment by sanishan** [comment]
anyone find a solution to work with HD video?

**Comment by mRYanna** [comment]
@arjunae Youtube changed the cipher again. Can you edit this patch to comply those changes please. Thanks...

**Comment by arjunae** [comment]
Yo: Confirmed. But as Youtube seems to change their stuff now on a regular, nearly Monthly base, i dont really feel that i like to do so.  Here are some steps so anyone interested can use to find the new positions:
1) start a youtube video - view html-source - search for the string /jsbin/player  
2) download or view above found player.js version : 
view-source:https://www.youtube.com/yts/jsbin/player-vflmQAIkc/de_DE/base.js
3) begin at last youtube changes Position - which also introduced "yt.akamaized.net" 
4) look at the stuff called after : "d.set(b,(0,window.encodeURIComponent)(pL((0,window.decodeURIComponent)(c))));return d};"
5) find analyze the function names b, pL , c
6) change the regexp.

Happy Hacking!...

**Comment by crsurfer** [comment]
hey@Athlon1600
1- thanks for creating this script! 
2- I'm trying to run this script but I can't get it to work properly. I get:

Invalid argument supplied for foreach()
` foreach ($instructions as $opt) {`
line 182

**Comment by Athlon1600** [comment]
^ that was fixed here:  
https://github.com/Athlon1600/youtube-downloader/commit/cf7f86346552f4834f96e6ec80677dae1d7bbc5a  
  
do: composer update to get the latest version

**Comment by crsurfer** [comment]
thanks @Athlon1600, I don't know much about  packages but if I do composer update, it doesn't really update the file. but for testing I did copy the code you had in that reference and worked. now I'm getting the URL, but I can't download any video ( access denied )

also this url : https://api.unblockvideos.com/youtube_downloader?id=4Ai63AkrZDk&selector=mp4&redirect=true has an exception.

**Comment by sfatfarma** [comment]
@Athlon1600 I love you, man!

**Comment by Athlon1600** [comment]
> I don't know much about packages but if I do composer update, it doesn't really update the file. 

Try removing your composer.lock file and doing composer update then.

> also this url : https://api.unblockvideos.com/youtube_downloader?id=4Ai63AkrZDk&selector=mp4&redirect=true has an exception.

That's because that video is private:

https://www.youtube.com/watch?v=4Ai63AkrZDk
image

**Comment by pdriss** [comment]
Thank you very much for your work !
Thanks to you, I have a system that works perfectly!
thanks again

**Comment by zxyu1010** [comment]
Hello my friend, I do not know how to create an application in Hiroki. Can you send an explanatory video about creating the application?

**Comment by Aniketh01** [comment]
How does this project find the manifest file?

**Comment by halocedark** [comment]
Thank you for this helpful package, however I can get the video to play inside html <video src="video_url"></video> tag, but I cannot download the video using anchor tag "<a></a>"

this is the code I use:

`<?php  

include_once '../vendor/autoload.php';

use YouTube\YouTubeDownloader;
use YouTube\Exception\YouTubeException;

$youtube = new YouTubeDownloader();

$output = '';

try {
    $links = $youtube->getDownloadLinks("https://www.youtube.com/watch?v=cWvR8zsNeDU&list=PLs2aOcA-EaLMzAOFn8ZFuZyq_It6StOOQ");
    $formats = $links->getAllFormats();
    if ($formats) 
    {
        $output .= '<video style="display: block;" width="'.$formats[1]->width.'" height="'.$formats[1]->height.'" controls>
					  <source src="'.$formats[1]->url.'" type="video/mp4">
					Your browser does not support the video tag.
					</video>';
		$output .= '<a href="'.$formats[1]->url.'" target="_blank" download style="display: block; padding: .5em 1em; margin: 1em 0 0 0;">Download</a>';
    } 
    else 
    {
        echo 'No links found';
    }

} catch (YouTubeException $e) {
    echo 'Something went wrong: ' . $e->getMessage();
}

echo $output;
`

When I click on download link, it simply open up new tab and play the video, but I don't want that, I simply want to trigger the browser to download the video.

Guys can you help me please?

**Pull request merged**
