### PR TITLE
Update client name and version in YouTubeDownloader@getPlayerApiResponse

### PR DESCRIPTION
**Pull request by rachid-essakhi**
Issue: #172

### CODE REVIEW

**Comment by alisaleem252** [comment]
But this generate links with access denied. i have tried that.

**Review by felipe-silveira-dev — APPROVED** [review]

**Comment by felipe-silveira-dev** [comment]
Its works to me but i'm using "clientName" => "ANDROID_EMBEDDED_PLAYER", that works too

**Comment by rachid-essakhi** [comment]
I user my PR in my project and it works just fine for me.

**Comment by Athlon1600** [comment]
That works 👍 

Lots of other working "clients" can be found here:  
https://github.com/yt-dlp/yt-dlp/blob/8213ce28a485e200f6a7e1af1434a987c8e702bd/yt_dlp/extractor/youtube.py#L71

**Pull request merged**
